# Generated by Django 2.1.7 on 2019-03-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0005_auto_20190322_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
